#!/bin/bash

BASEDIR=`dirname "$(realpath -s $0)"`
export BASEDIR
FILES="-f ${BASEDIR}/docker/docker-compose.yml -f ${BASEDIR}/docker/docker-compose.dev.yml"
if [ -f $BASEDIR/docker/docker-compose.override.yml ]
then
    FILES="${FILES} -f ${BASEDIR}/docker/docker-compose.override.yml"
fi
docker-compose -p optimouv $FILES "$*"
