# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            remember_me:
                key:   '%secret%'
                lifetime: 604800 # 1 week in seconds
            form_login:
                login_path: /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
                #activer l'option remember me
                remember_me: true
                require_previous_session: false
                provider: fos_userbundle
                #csrf_token_generator: security.csrf.token_manager
                csrf_provider: form.csrf_provider
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:
                path: /logout
                target: /
            anonymous:    true

    access_control:
#    accéder d'une manière anonyme
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }


#    accéder avec le profil admin général
        - { path: ^/admin/discipline/, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/federation/, role: ROLE_SUPER_ADMIN }

#    accéder avec le profil admin fédéral
        - { path: ^/administration/gestion/, role: ROLE_ADMIN }
        - { path: ^/administration/gestion/users/, role: ROLE_ADMIN }


#    accéder avec le profil user
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/administration/gestion/users/edit/, role: ROLE_USER }

