# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    service_rencontres:
        class: Optimouv\FfbbBundle\Services\Rencontres
        arguments: ["%database_host%", "%database_name%", "%database_user%", "%database_password%", "%app_id%", "%app_code%", "%error_log_path%", "@service_statistiques", "%here_request_limit%"]

    service_listes:
        class: Optimouv\FfbbBundle\Services\Listes
        arguments: ["%database_host%", "%database_name%", "%database_user%", "%database_password%", "%app_id%", "%app_code%", "%error_log_path%"]

    service_poules:
        class: Optimouv\FfbbBundle\Services\Poules
        arguments: ["%database_host%", "%database_name%", "%database_user%", "%database_password%", "%app_id%", "%app_code%", "%error_log_path%", "@service_statistiques", "@service_fonctions_communes" ]

    service_calcul_rencontre:
        class: Optimouv\FfbbBundle\Services\CalculRencontreConsumer
        arguments: ["%database_host%", "%database_name%", "%database_user%", "%database_password%", "%app_id%", "%app_code%", "%error_log_path%", "@service_container", "@mailer", "@templating", "@service_statistiques", "%mailer_user%", "%base_url%", "%mailer_sender%", "%here_request_limit%", "%sender_name%" ]

    service_statistiques:
        class: Optimouv\FfbbBundle\Services\Statistiques
        arguments: ["%database_host%", "%database_name%", "%database_user%", "%database_password%", "%error_log_path%"]

    login_success_handler:
          class: Optimouv\AdminBundle\Services\LoginSuccessHandler
          arguments: ["@router", "@doctrine.orm.entity_manager", "@security.authorization_checker", "@service_statistiques", "%max_number_active_users%", "%time_limit_active_users%", "%error_log_path%"]

    service_rapports:
          class: Optimouv\FfbbBundle\Services\Rapports
          arguments: ["%database_host%", "%database_name%", "%database_user%", "%database_password%", "%error_log_path%"]

    activity_listener:
          class: Optimouv\FfbbBundle\Services\ActivityListener
          arguments: ["@security.authorization_checker", "@security.token_storage" , "@doctrine.orm.entity_manager", "%time_limit_active_users%"]
          tags:
              - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    service_fonctions_communes:
        class: Optimouv\FfbbBundle\Services\FonctionsCommunes
        arguments: ["%database_host%", "%database_name%", "%database_user%", "%database_password%", "%error_log_path%"]
