# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    service_rencontres:
        class: Optimouv\FfbbBundle\Services\Rencontres
        arguments: ["%database_name%", "%database_user%", "%database_password%", "%app_id%", "%app_code%", "%error_log_path%" ]

    service_listes:
            class: Optimouv\FfbbBundle\Services\Listes
            arguments: ["%database_name%", "%database_user%", "%database_password%", "%app_id%", "%app_code%", "%error_log_path%"]

    service_poules:
            class: Optimouv\FfbbBundle\Services\Poules
            arguments: ["%database_name%", "%database_user%", "%database_password%", "%app_id%", "%app_code%", "%error_log_path%"]

    service_calcul_rencontre:
                class: Optimouv\FfbbBundle\Services\CalculRencontreConsumer
                arguments: ["%database_name%", "%database_user%", "%database_password%", "%app_id%", "%app_code%", "%error_log_path%", "@service_container", "@mailer", "@templating"]

    login_success_handler:
          class: Optimouv\AdminBundle\Services\LoginSuccessHandler
          arguments: [@router, @security.authorization_checker, "%database_name%", "%database_user%", "%database_password%", "%error_log_path%"]
