version: '2'

services:
  webserver:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ${BASEDIR}:/optimouv
      - ./nginx/optimouv.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - phpfastcgi
      - rabbitmq
      - phpmyadmin

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: myPass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mysql/optimouv.cnf:/etc/mysql/conf.d/optimouv.cnf:ro

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: mq

  phpfastcgi:
    build: ./php
    volumes:
      - ${BASEDIR}:/optimouv
    links:
      - mysql
      - rabbitmq

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql

  worker_mailer:
    build: ./php
    volumes:
      - ${BASEDIR}:/optimouv
    links:
      - mysql
      - rabbitmq
    restart: always
    working_dir: /optimouv/workers
    user: www-data
    command: ["/optimouv/workers/mailer.sh"]

  worker_bestplace:
    build: ./php
    volumes:
      - ${BASEDIR}:/optimouv
    links:
      - mysql
      - rabbitmq
    restart: always
    working_dir: /optimouv/workers
    user: www-data
    command: ["/optimouv/workers/bestplace.sh"]

  worker_optimisations:
    build: ./python
    volumes:
      - ${BASEDIR}:/optimouv
    links:
      - mysql
      - rabbitmq
    restart: always
    working_dir: /optimouv/workers/
    command: ["/optimouv/workers/optimization.sh"]

  doc:
    build: ./mkdocs
    volumes:
      - ${BASEDIR}:/src
    ports:
      - 8002:8000
