# Exemple de surcharge des paramètres
version: '2'

services:
  # Expose NGinx sur le port 80
  webserver:
    ports:
      - 80:80

  # Défini un mot de passe pour MySQL
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: newPass

  # Défini un mot de passe pour RabbitMQ
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: rabbitpassword
