admin_reset_password:
    path:     /reset-password
    defaults: { _controller: AdminBundle:Resetting:index }

admin_update_password:
    path:     /update-password/{idUser}
    defaults: { _controller: AdminBundle:Resetting:update }

admin_update_password_user:
    path:     /update-password-user/
    defaults: { _controller: AdminBundle:Resetting:updatePwd }

admin_user_add:
    path:     /user-add/
    defaults: { _controller: AdminBundle:User:userAdd }

admin_user_create:
    path:     /user-create/
    defaults: { _controller: AdminBundle:User:userCreate }

admin_user_activate:
    path:     /user-activate/{$id}
    defaults: { _controller: AdminBundle:User:userActivate }