<?php

namespace Optimouv\AdminBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function activateUser($idUser){
        

        $query = $this->createQueryBuilder('G')
            ->update('AdminBundle:User', 'u')
            ->set('u.enabled' , '?1')
            ->set('u.locked' , '?2')
            ->where('u.id = ?3')
            ->setParameter(1, true)
            ->setParameter(2, false)
            ->setParameter(3, $idUser)
            ->getQuery();

        $activation = $query->execute();

        return $activation;
    }

   

    
}

