<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * EntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntiteRepository extends \Doctrine\ORM\EntityRepository
{
}
