<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * DisciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntiteRepository extends \Doctrine\ORM\EntityRepository
{

    public function getDetailsPourEntite($idEntite){
        $query = $this->createQueryBuilder('e')
            ->select('e.nom, e.codePostal')
            ->where('e.id= :id')
            ->setParameter('id', $idEntite)
            ->getQuery();

        $result = $query->getResult();

        return $result;
    }

}