<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * FederationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FederationRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateFede($params){
        
         $id = $params[0];
         $nom = $params[1];
         $designation = $params[2];
        
        $query = $this->createQueryBuilder('G')
            ->update('FfbbBundle:Federation', 'f')
            ->set('f.nom' , '?1')
            ->set('f.designation' , '?2')
            ->where('f.id = ?3')
            ->setParameter(1, $nom)
            ->setParameter(2, $designation)
            ->setParameter(3, $id)
            ->getQuery();

        $update = $query->execute();

        return $update;
    }

    public function getAllList()
    {
        $query = $this->createQueryBuilder('f')
            ->join('f.disciplines', 'd')
            ->getQuery();
        $result = $query->getResult();
        return $result;
    }

  

    
}

