<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * LieuRencontreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuRencontreRepository extends \Doctrine\ORM\EntityRepository
{
}
