<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * ListeParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeParticipantsRepository extends \Doctrine\ORM\EntityRepository
{
}
