<?php

namespace Optimouv\FfbbBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * ListeLieuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeLieuxRepository extends EntityRepository
{

    public function getListes(){

        $query = $this->createQueryBuilder('l')
            ->select('l.id, l.nom')
            ->getQuery();

        $result = $query->getResult();

        return $result;

    }

    public function getEquipesPourListe($idListe){
        $query = $this->createQueryBuilder('l')
            ->select('l.lieux')
            ->where('l.id= :id')
            ->setParameter('id', $idListe)
            ->getQuery();

        $result = $query->getResult();

        return $result;
    }

}
