<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * ListeLieuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeLieuxRepository extends \Doctrine\ORM\EntityRepository
{
}
