<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * RapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRapportsParIdGroupe($idGroupes){
        $query = $this->createQueryBuilder('r')
            ->select('r.id, r.nom, identity(r.idGroupe) as idGroupe, r.typeAction, r.params, r.dateCreation')
            ->where('r.idGroupe IN (:idGroupe)')
            ->setParameter('idGroupe', array_values($idGroupes))
            ->orderBy('r.id', 'DESC')
            ->getQuery();
        $result = $query->getResult();

        return $result;
    }

    public function getStatut($idTache)
    {

        $query = $this->createQueryBuilder('t')
            ->select('t.statut')
            ->where('t.id = :id')
            ->setParameter('id', $idTache)
             ->getQuery();
        $result = $query->getResult();

        return $result;

    }

    public function getIdGroupe($idRapport)
    {

        $query = $this->createQueryBuilder('t')
            ->select('IDENTITY (t.idGroupe) as idGroupe')
            ->where('t.id = :id')
            ->setParameter('id', $idRapport)
            ->getQuery();
        $result = $query->getResult();

        return $result;

    }

    public function getInfosExclusion($idRapport)
    {

        $query = $this->createQueryBuilder('t')
            ->select('IDENTITY (t.idGroupe) as idGroupe, t.params')
            ->where('t.id = :id')
            ->setParameter('id', $idRapport)
            ->getQuery();
        $result = $query->getResult();

        return $result;

    }

    public function getTypeAction($idRapport)
    {

        $query = $this->createQueryBuilder('t')
            ->select('t.typeAction')
            ->where('t.id = :id')
            ->setParameter('id', $idRapport)
            ->getQuery();
        $result = $query->getResult();

        return $result;

    }

    public function updateRapport($nom, $id){

        $query = $this->createQueryBuilder('G')
            ->update('FfbbBundle:Rapport', 'd')
            ->set('d.nom' , '?1')
            ->where('d.id = ?2')
            ->setParameter(1, $nom)
            ->setParameter(2, $id)
            ->getQuery();

        $update = $query->execute();

        return $update;
    }
}
