<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * RapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRapportsParIdGroupe($idGroupes){
        $query = $this->createQueryBuilder('r')
            ->select('r.id, r.nom, r.typeAction, r.valeurExclusion, r.dateCreation')
            ->where('r.idGroupe IN (:idGroupe)')
            ->setParameter('idGroupe', array_values($idGroupes))
            ->orderBy('r.id', 'DESC')
            ->getQuery();
        $result = $query->getResult();

        return $result;
    }

}
