<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * RepartitionHomogeneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepartitionHomogeneRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateCat($designation, $id){

        $query = $this->createQueryBuilder('G')
            ->update('FfbbBundle:RepartitionHomogene', 'd')
            ->set('d.designation' , '?1')
            ->where('d.id = ?2')
            ->setParameter(1, $designation)
            ->setParameter(2, $id)
            ->getQuery();

        $update = $query->execute();

        return $update;
    }
}
