<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * DisciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDetailsCalcul($idTache)
    {

        $query = $this->createQueryBuilder('t')
            ->select('t.detailsCalcul')
            ->where('t.idRapport = :id')
            ->setParameter('id', $idTache)
            ->getQuery();
        $result = $query->getResult();

        return $result;

    }
}