<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * StatistiquesDateTempsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiquesDateTempsRepository extends \Doctrine\ORM\EntityRepository
{
}
