<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * StatistiquesDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiquesDateRepository extends \Doctrine\ORM\EntityRepository
{
}
