<?php

namespace Optimouv\FfbbBundle\Entity;

/**
 * VillesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesRepository extends \Doctrine\ORM\EntityRepository
{
}
